language: cpp
sudo: required
dist: trusty
script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make
compiler:
    - gcc-5
before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq libyajl-dev libxml2-dev libxqilla-dev
    - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-5-dev; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
branches:
    only:
        - master
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
